# Uitleg van de hele code en het dashboard

**Voor iemand die ongeveer 1 maand een data-analyse cursus heeft gevolgd**

In dit notebook leggen we stap voor stap uit:
- welke bestanden belangrijk zijn
- hoe de data wordt opgehaald en samengevoegd
- hoe de Streamlit-app is opgebouwd
- wat elke grafiek en tabel doet
- welke stukken code je als beginner echt moet begrijpen

We houden de uitleg bewust simpel. Het doel is niet om moeilijke woorden te gebruiken,
maar om te snappen **wat de code doet** en **waarom**.

In [1]:
import sys
from pathlib import Path
import pandas as pd

sys.path.insert(0, r"c:\Users\AAchr\Documents\Casus 2 phyton minor\ROC")

from data import laad_alle_data, ADVIES_TYPEN, SCHOOLJAREN

pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 200)

wijken_df, duo_df, scholen_df, bronnen = laad_alle_data()

print("Bronnen:")
for naam, bron in bronnen.items():
    print(f"- {naam}: {bron}")

print()
print("Aantal rijen:")
print("wijken_df:", len(wijken_df))
print("duo_df:", len(duo_df))
print("scholen_df:", len(scholen_df))

2026-04-06 19:10:57.140 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

2026-04-06 19:10:57.142 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

2026-04-06 19:10:57.143 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

2026-04-06 19:10:57.144 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

2026-04-06 19:10:57.145 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

2026-04-06 19:10:57.146 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

2026-04-06 19:10:57.147 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

2026-04-06 19:10:57.147 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

2026-04-06 19:10:57.391 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

2026-04-06 19:10:57.950 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

Bronnen:
- CBS Kerncijfers Wijken en Buurten 2024: Live data van CBS OData API (samengevoegd naar dashboardwijken)
- DUO Schooladviezen per school: Live data van DUO Open Onderwijsdata (adviescodes samengevoegd, bijstelling niet apart beschikbaar)
- Amsterdam schoolgebouwen: Live data van Amsterdam schoolgebouwen API

Aantal rijen:
wijken_df: 22
duo_df: 2971
scholen_df: 214

## 1. Welke bestanden zijn belangrijk?

Voor dit project zijn vooral deze 2 bestanden belangrijk:

- `data.py`
  Hier wordt de data opgehaald, opgeschoond en samengevoegd.
- `app.py`
  Hier wordt de Streamlit-app gebouwd: tabs, filters, grafieken en tabellen.

Je kunt het zo zien:

- `data.py` = de **keuken**
- `app.py` = het **restaurant**

Eerst wordt in de keuken alles voorbereid. Daarna laat het restaurant het netjes aan de gebruiker zien.

In [2]:
def toon_regels(bestand, start, einde):
    """Laat een stukje code zien met regelnummers."""
    regels = Path(bestand).read_text(encoding="utf-8").splitlines()
    for i in range(start - 1, einde):
        print(f"{i+1:>4}: {regels[i]}")

## 2. Uitleg van `data.py`

Dit bestand doet 4 hoofdzaken:

1. vaste lijsten en kleuren maken
2. live data ophalen van CBS
3. live data ophalen van DUO en Amsterdam
4. alles samenvoegen tot datasets die de app kan gebruiken

Dat zijn goede beginnerstappen:
- eerst data ophalen
- dan kolommen gelijk maken
- dan datasets koppelen
- dan pas grafieken bouwen

In [3]:
print("Belangrijke start van data.py")
toon_regels("data.py", 1, 120)

Belangrijke start van data.py
   1: # data.py
   2: # Gemaakt door: Groep 2
   3: # Hier halen we alle data op die we nodig hebben voor ons dashboard.
   4: # We gebruiken drie bronnen:
   5: #   1. CBS OData API  - inkomen en achtergrond per wijk
   6: #   2. DUO Open Data  - schooladviezen per school per jaar
   7: #   3. Amsterdam API  - schoollocaties met stadsdeel info
   8:
   9: import requests
  10: import pandas as pd
  11: import numpy as np
  12: import streamlit as st
  13:
  14: # alle adviestypen in volgorde van laag naar hoog
  15: ADVIES_TYPEN = [
  16:     "Praktijkonderwijs",
  17:     "VMBO-BBL",
  18:     "VMBO-KBL",
  19:     "VMBO-TL",
  20:     "VMBO-TL/HAVO",
  21:     "HAVO",
  22:     "HAVO/VWO",
  23:     "VWO",
  24: ]
  25:
  26: # kleur per adviestype (rood = laag, groen = hoog)
  27: ADVIES_KLEUREN = {
  28:     "Praktijkonderwijs": "#d73027",
  29:     "VMBO-BBL":          "#f46d43",
  30:     "VMBO-KBL":          "#fdae61",
  31:     "VMBO-TL":           "#fee08b",
  32:     "VMBO-TL/HAVO":      "#d9ef8b",
  33:     "HAVO":              "#66bd63",
  34:     "HAVO/VWO":          "#1a9850",
  35:     "VWO":               "#006837",
  36: }
  37:
  38: SCHOOLJAREN = ["2018-2019", "2019-2020", "2020-2021", "2021-2022", "2022-2023", "2023-2024"]
  39:
  40: # De live DUO-data gebruikt numerieke adviescodes. Voor dit dashboard zetten we die
  41: # grof om naar dezelfde 8 categorieen als in de rest van de app.
  42: DUO_ADVIES_NAAR_TYPE = {
  43:     1:  "Praktijkonderwijs",
  44:     2:  "VMBO-BBL",
  45:     3:  "VMBO-BBL",
  46:     4:  "VMBO-KBL",
  47:     5:  "VMBO-KBL",
  48:     6:  "VMBO-TL",
  49:     7:  "VMBO-TL",
  50:     8:  "VMBO-TL/HAVO",
  51:     9:  "HAVO",
  52:     10: "HAVO",
  53:     11: "HAVO/VWO",
  54:     12: "VWO",
  55: }
  56:
  57:
  58: def koppel_cbs_code_aan_dashboard(wijk_code):
  59:     code = str(wijk_code).strip()
  60:
  61:     if code.startswith("WK0363A"):
  62:         return "Centrum"
  63:     if code.startswith("WK0363B"):
  64:         return "Westelijk Havengebied"
  65:
  66:     if code in ["WK0363EA", "WK0363EB", "WK0363EC", "WK0363ED", "WK0363EE"]:
  67:         return "Westerpark"
  68:     if code in ["WK0363EF", "WK0363EG", "WK0363EH", "WK0363EJ", "WK0363EK"]:
  69:         return "Bos en Lommer"
  70:     if code.startswith("WK0363E"):
  71:         return "Oud-West / De Baarsjes"
  72:
  73:     if code in ["WK0363FA", "WK0363FB", "WK0363FC", "WK0363FD", "WK0363FE"]:
  74:         return "Geuzenveld-Slotermeer"
  75:     if code in ["WK0363FF", "WK0363FG", "WK0363FH", "WK0363FJ", "WK0363FK"]:
  76:         return "Osdorp"
  77:     if code in ["WK0363FL", "WK0363FM", "WK0363FN"]:
  78:         return "Slotervaart"
  79:     if code in ["WK0363FP", "WK0363FQ"]:
  80:         return "Aker, Sloten en Nieuw Sloten"
  81:
  82:     if code in ["WK0363KA", "WK0363KB", "WK0363KC", "WK0363KD"]:
  83:         return "Oud-Zuid"
  84:     if code in ["WK0363KE", "WK0363KF", "WK0363KG", "WK0363KH"]:
  85:         return "De Pijp / Rivierenbuurt"
  86:     if code in ["WK0363KJ", "WK0363KK", "WK0363KL", "WK0363KM"]:
  87:         return "Buitenveldert / Zuidas"
  88:     if code in ["WK0363KN", "WK0363KP", "WK0363KQ", "WK0363KR"]:
  89:         return "Zuideramstel"
  90:
  91:     if code in ["WK0363MA", "WK0363MB", "WK0363MC", "WK0363MD"]:
  92:         return "Watergraafsmeer"
  93:     if code in ["WK0363ME", "WK0363MF", "WK0363MG", "WK0363MH"]:
  94:         return "Indische Buurt"
  95:     if code in ["WK0363MJ", "WK0363MK", "WK0363ML"]:
  96:         return "IJburg / Zeeburgereiland"
  97:     if code in ["WK0363MM", "WK0363MN", "WK0363MP", "WK0363MQ"]:
  98:         return "De Omval / Overamstel"
  99:
 100:     if code in ["WK0363NA", "WK0363NB", "WK0363NC", "WK0363ND", "WK0363NE", "WK0363NF", "WK0363NG"]:
 101:         return "Noord-West"
 102:     if code in ["WK0363NH", "WK0363NJ", "WK0363NK", "WK0363NL", "WK0363NM", "WK0363NN", "WK0363NP", "WK0363NQ"]:
 103:         return "Noord-Oost"
 104:
 105:     if code in ["WK0363TA", "WK0363TB", "WK0363TC", "WK0363TD"]:
 106:         return "Bijlmer-Centrum"
 107:     if code in ["WK0363TE", "WK0363TF", "WK0363TG", "WK0363TH"]:
 108:         return "Bijlmer-Oost"
 109:     if code in ["WK0363TJ", "WK0363TK", "WK0363TL", "WK0363TM"]:
 110:         return "Gaasperdam / Driemond"
 111:
 112:     return None
 113:
 114:
 115: # ---------------------------------------------------------------
 116: # 1. CBS data ophalen - inkomen, niet-westerse achtergrond etc.
 117: # ---------------------------------------------------------------
 118:
 119: @st.cache_data(ttl=86400)
 120: def haal_cbs_data_op():

### 2.1 Vaste lijsten en kleuren

Bovenin `data.py` staan vaste dingen zoals:
- `ADVIES_TYPEN`
- `ADVIES_KLEUREN`
- `SCHOOLJAREN`

Waarom is dat handig?

Omdat je die informatie daarna op meerdere plekken opnieuw kunt gebruiken.
Bijvoorbeeld:
- in filters
- in grafieken
- in legenda's
- in berekeningen

Dat voorkomt dat je op 5 plekken steeds dezelfde lijst opnieuw moet typen.

### 2.2 CBS-data

De functie `haal_cbs_data_op()` haalt wijkgegevens op, zoals:
- inkomen
- aantal inwoners
- aandeel niet-westerse achtergrond
- opleidingsniveau
- uitkering
- WOZ-waarde

Belangrijk om te begrijpen:

De live CBS-data gebruikt **andere wijkcodes** dan jullie dashboard.
Daarom wordt de live data later omgezet naar jullie eigen wijkgroepen.
Dat is een heel normale stap in data-analyse:
de brondata past niet altijd meteen op jouw onderzoeksvraag.

In [4]:
print("CBS-functies in data.py")
toon_regels("data.py", 40, 185)

CBS-functies in data.py
  40: # De live DUO-data gebruikt numerieke adviescodes. Voor dit dashboard zetten we die
  41: # grof om naar dezelfde 8 categorieen als in de rest van de app.
  42: DUO_ADVIES_NAAR_TYPE = {
  43:     1:  "Praktijkonderwijs",
  44:     2:  "VMBO-BBL",
  45:     3:  "VMBO-BBL",
  46:     4:  "VMBO-KBL",
  47:     5:  "VMBO-KBL",
  48:     6:  "VMBO-TL",
  49:     7:  "VMBO-TL",
  50:     8:  "VMBO-TL/HAVO",
  51:     9:  "HAVO",
  52:     10: "HAVO",
  53:     11: "HAVO/VWO",
  54:     12: "VWO",
  55: }
  56:
  57:
  58: def koppel_cbs_code_aan_dashboard(wijk_code):
  59:     code = str(wijk_code).strip()
  60:
  61:     if code.startswith("WK0363A"):
  62:         return "Centrum"
  63:     if code.startswith("WK0363B"):
  64:         return "Westelijk Havengebied"
  65:
  66:     if code in ["WK0363EA", "WK0363EB", "WK0363EC", "WK0363ED", "WK0363EE"]:
  67:         return "Westerpark"
  68:     if code in ["WK0363EF", "WK0363EG", "WK0363EH", "WK0363EJ", "WK0363EK"]:
  69:         return "Bos en Lommer"
  70:     if code.startswith("WK0363E"):
  71:         return "Oud-West / De Baarsjes"
  72:
  73:     if code in ["WK0363FA", "WK0363FB", "WK0363FC", "WK0363FD", "WK0363FE"]:
  74:         return "Geuzenveld-Slotermeer"
  75:     if code in ["WK0363FF", "WK0363FG", "WK0363FH", "WK0363FJ", "WK0363FK"]:
  76:         return "Osdorp"
  77:     if code in ["WK0363FL", "WK0363FM", "WK0363FN"]:
  78:         return "Slotervaart"
  79:     if code in ["WK0363FP", "WK0363FQ"]:
  80:         return "Aker, Sloten en Nieuw Sloten"
  81:
  82:     if code in ["WK0363KA", "WK0363KB", "WK0363KC", "WK0363KD"]:
  83:         return "Oud-Zuid"
  84:     if code in ["WK0363KE", "WK0363KF", "WK0363KG", "WK0363KH"]:
  85:         return "De Pijp / Rivierenbuurt"
  86:     if code in ["WK0363KJ", "WK0363KK", "WK0363KL", "WK0363KM"]:
  87:         return "Buitenveldert / Zuidas"
  88:     if code in ["WK0363KN", "WK0363KP", "WK0363KQ", "WK0363KR"]:
  89:         return "Zuideramstel"
  90:
  91:     if code in ["WK0363MA", "WK0363MB", "WK0363MC", "WK0363MD"]:
  92:         return "Watergraafsmeer"
  93:     if code in ["WK0363ME", "WK0363MF", "WK0363MG", "WK0363MH"]:
  94:         return "Indische Buurt"
  95:     if code in ["WK0363MJ", "WK0363MK", "WK0363ML"]:
  96:         return "IJburg / Zeeburgereiland"
  97:     if code in ["WK0363MM", "WK0363MN", "WK0363MP", "WK0363MQ"]:
  98:         return "De Omval / Overamstel"
  99:
 100:     if code in ["WK0363NA", "WK0363NB", "WK0363NC", "WK0363ND", "WK0363NE", "WK0363NF", "WK0363NG"]:
 101:         return "Noord-West"
 102:     if code in ["WK0363NH", "WK0363NJ", "WK0363NK", "WK0363NL", "WK0363NM", "WK0363NN", "WK0363NP", "WK0363NQ"]:
 103:         return "Noord-Oost"
 104:
 105:     if code in ["WK0363TA", "WK0363TB", "WK0363TC", "WK0363TD"]:
 106:         return "Bijlmer-Centrum"
 107:     if code in ["WK0363TE", "WK0363TF", "WK0363TG", "WK0363TH"]:
 108:         return "Bijlmer-Oost"
 109:     if code in ["WK0363TJ", "WK0363TK", "WK0363TL", "WK0363TM"]:
 110:         return "Gaasperdam / Driemond"
 111:
 112:     return None
 113:
 114:
 115: # ---------------------------------------------------------------
 116: # 1. CBS data ophalen - inkomen, niet-westerse achtergrond etc.
 117: # ---------------------------------------------------------------
 118:
 119: @st.cache_data(ttl=86400)
 120: def haal_cbs_data_op():
 121:     # CBS OData v3 API - Kerncijfers Wijken en Buurten 2024 (tabel 85984NED)
 122:     # We filteren op Amsterdam wijken (code begint met WK0363)
 123:     # Bron: https://opendata.cbs.nl/ODataApi/odata/85984NED/TypedDataSet
 124:     # (odata4.cbs.nl doet het niet meer; v3 via opendata.cbs.nl werkt wel)
 125:     url = "https://opendata.cbs.nl/ODataApi/odata/85984NED/TypedDataSet"
 126:     params = {
 127:         "$filter": "startswith(WijkenEnBuurten,'WK0363')",
 128:         "$format": "json",
 129:         "$top": 200
 130:     }
 131:
 132:     try:
 133:         antwoord = requests.get(url, params=params, timeout=20)
 134:         antwoord.raise_for_status()
 135:         records = antwoord.json().get("value", [])
 136:
 137:         if len(records) > 0:
 138:             df = pd.DataFrame(records)
 139:             # kolommen hernoemen zodat we ze makkelijk kunnen gebruiken
 140:             hernoem = {}
 141:             al_gebruikt = set()  # voorkomt dat twee kolommen dezelfde naam krijgen
 142:             for kolom in df.columns:
 143:                 k = kolom.lower()
 144:                 nieuwe_naam = None
 145:                 # CBS v3: regio-veld heet WijkenEnBuurten; v4 gebruikt RegioS
 146:                 if kolom in ("RegioS", "WijkenEnBuurten"):
 147:                     nieuwe_naam = "wijk_code"
 148:                 elif "inkomen" in k and "gemiddeld" in k and "ontvanger" in k:
 149:                     nieuwe_naam = "gem_inkomen"  # GemiddeldInkomenPerInkomensontvanger
 150:                 elif "inwoners" in k and "aantal" in k:
 151:                     nieuwe_naam = "aantal_inwoners"
 152:                 elif "nietwester" in k.replace(" ", "").replace("-", "") or \
 153:                      ("buiten" in k and "europa" in k):
 154:                     nieuwe_naam = "pct_niet_westers"
 155:                 elif "bijstand" in k or ("uitkering" in k and "relatief" in k) or \
 156:                      ("bijstand" in k and "personen" in k):
 157:                     nieuwe_naam = "pct_uitkering"
 158:                 elif ("basisonderwijs" in k or "vmbo" in k or "mbo1" in k) and \
 159:                      ("laag" in k or "basis" in k or "vmbo" in k):
 160:                     nieuwe_naam = "pct_laag_opgeleid"
 161:                 elif ("hbo" in k or "wo" in k) and ("hoog" in k or "hbo" in k):
 162:                     nieuwe_naam = "pct_hoog_opgeleid"
 163:                 elif "woz" in k and "gemiddeld" in k:
 164:                     nieuwe_naam = "gem_woz"
 165:                 if nieuwe_naam and nieuwe_naam not in al_gebruikt:
 166:                     hernoem[kolom] = nieuwe_naam
 167:                     al_gebruikt.add(nieuwe_naam)
 168:             df = df.rename(columns=hernoem)
 169:
 170:             # verwijder dubbele wijk_code kolom als die er is (RegioS en WijkenEnBuurten
 171:             # kunnen allebei aanwezig zijn in sommige CBS-versies)
 172:             if df.columns.duplicated().any():
 173:                 df = df.loc[:, ~df.columns.duplicated()]
 174:
 175:             df["wijk_code"] = df["wijk_code"].astype(str).str.strip()
 176:             df["wijk_naam"] = df["wijk_code"].apply(koppel_cbs_code_aan_dashboard)
 177:             df = df[df["wijk_naam"].notna()].copy()
 178:
 179:             nooddata = maak_cbs_nooddata()
 180:             wijk_info = nooddata[["wijk_code", "wijk_naam", "stadsdeel", "lat", "lon"]]
 181:
 182:             numerieke_kolommen = []
 183:             overslaan = ["ID", "wijk_code", "wijk_naam", "Gemeentenaam_1", "SoortRegio_2", "Codering_3"]
 184:             for kolom in df.columns:
 185:                 if kolom in overslaan:

### 2.3 DUO-data

De DUO-data gaat over schooladviezen.

Daar zie je per school en per jaar:
- hoeveel leerlingen een bepaald advies kregen

In jullie code worden numerieke DUO-codes vertaald naar begrijpelijke adviesgroepen, zoals:
- `VMBO-BBL`
- `VMBO-KBL`
- `VMBO-TL`
- `HAVO`
- `HAVO/VWO`
- `VWO`

Dat is belangrijk, want gebruikers willen geen code `7` of `11` zien,
maar een echte naam.

In [5]:
print("DUO-functies in data.py")
toon_regels("data.py", 150, 290)

DUO-functies in data.py
 150:                 elif "inwoners" in k and "aantal" in k:
 151:                     nieuwe_naam = "aantal_inwoners"
 152:                 elif "nietwester" in k.replace(" ", "").replace("-", "") or \
 153:                      ("buiten" in k and "europa" in k):
 154:                     nieuwe_naam = "pct_niet_westers"
 155:                 elif "bijstand" in k or ("uitkering" in k and "relatief" in k) or \
 156:                      ("bijstand" in k and "personen" in k):
 157:                     nieuwe_naam = "pct_uitkering"
 158:                 elif ("basisonderwijs" in k or "vmbo" in k or "mbo1" in k) and \
 159:                      ("laag" in k or "basis" in k or "vmbo" in k):
 160:                     nieuwe_naam = "pct_laag_opgeleid"
 161:                 elif ("hbo" in k or "wo" in k) and ("hoog" in k or "hbo" in k):
 162:                     nieuwe_naam = "pct_hoog_opgeleid"
 163:                 elif "woz" in k and "gemiddeld" in k:
 164:                     nieuwe_naam = "gem_woz"
 165:                 if nieuwe_naam and nieuwe_naam not in al_gebruikt:
 166:                     hernoem[kolom] = nieuwe_naam
 167:                     al_gebruikt.add(nieuwe_naam)
 168:             df = df.rename(columns=hernoem)
 169:
 170:             # verwijder dubbele wijk_code kolom als die er is (RegioS en WijkenEnBuurten
 171:             # kunnen allebei aanwezig zijn in sommige CBS-versies)
 172:             if df.columns.duplicated().any():
 173:                 df = df.loc[:, ~df.columns.duplicated()]
 174:
 175:             df["wijk_code"] = df["wijk_code"].astype(str).str.strip()
 176:             df["wijk_naam"] = df["wijk_code"].apply(koppel_cbs_code_aan_dashboard)
 177:             df = df[df["wijk_naam"].notna()].copy()
 178:
 179:             nooddata = maak_cbs_nooddata()
 180:             wijk_info = nooddata[["wijk_code", "wijk_naam", "stadsdeel", "lat", "lon"]]
 181:
 182:             numerieke_kolommen = []
 183:             overslaan = ["ID", "wijk_code", "wijk_naam", "Gemeentenaam_1", "SoortRegio_2", "Codering_3"]
 184:             for kolom in df.columns:
 185:                 if kolom in overslaan:
 186:                     continue
 187:                 df[kolom] = pd.to_numeric(df[kolom], errors="coerce")
 188:                 if pd.api.types.is_numeric_dtype(df[kolom]):
 189:                     numerieke_kolommen.append(kolom)
 190:
 191:             aggregaties = {}
 192:             for kolom in numerieke_kolommen:
 193:                 if kolom == "aantal_inwoners":
 194:                     aggregaties[kolom] = "sum"
 195:                 else:
 196:                     aggregaties[kolom] = "mean"
 197:
 198:             df = df.groupby("wijk_naam", as_index=False).agg(aggregaties)
 199:
 200:             # Een paar live CBS-velden zijn aantallen. Voor dit dashboard maken we daar
 201:             # eenvoudige percentages van zodat ze beter aansluiten op de rest van de app.
 202:             if "pct_niet_westers" in df.columns and "aantal_inwoners" in df.columns:
 203:                 df["pct_niet_westers"] = (df["pct_niet_westers"] / df["aantal_inwoners"] * 100).round(1)
 204:             if "pct_uitkering" in df.columns and "aantal_inwoners" in df.columns:
 205:                 df["pct_uitkering"] = (df["pct_uitkering"] / df["aantal_inwoners"] * 100).round(1)
 206:             if "pct_hoog_opgeleid" in df.columns and "pct_laag_opgeleid" in df.columns and "HavoVwoMbo24_68" in df.columns:
 207:                 totaal_opleiding = df["pct_laag_opgeleid"] + df["HavoVwoMbo24_68"] + df["pct_hoog_opgeleid"]
 208:                 df["pct_hoog_opgeleid"] = (df["pct_hoog_opgeleid"] / totaal_opleiding * 100).round(1)
 209:                 df["pct_laag_opgeleid"] = (df["pct_laag_opgeleid"] / totaal_opleiding * 100).round(1)
 210:
 211:             df = wijk_info.merge(df, on="wijk_naam", how="left")
 212:
 213:             return df, "Live data van CBS OData API (samengevoegd naar dashboardwijken)"
 214:
 215:     except Exception as fout:
 216:         pass  # als de API niet werkt gaan we door naar de nooddata
 217:
 218:     # als de API niet werkt gebruiken we onze eigen data
 219:     # deze data is gebaseerd op echte Amsterdamse CBS-cijfers uit 2023
 220:     return maak_cbs_nooddata(), "Eigen data (CBS API niet bereikbaar)"
 221:
 222:
 223: def maak_cbs_nooddata():
 224:     # Amsterdamse wijken met echte kenmerken
 225:     # bronnen: OIS Amsterdam 2023, CBS Kerncijfers 2023
 226:     wijken = [
 227:         # (wijk_code, wijk_naam, stadsdeel, gem_inkomen (x1000), pct_niet_westers,
 228:         #  pct_uitkering, pct_hoog_opgeleid, pct_laag_opgeleid, gem_woz, lat, lon)
 229:         ("WK036300", "Centrum",                        "Centrum",    38, 20,  8, 55, 12, 560, 52.373, 4.893),
 230:         ("WK036301", "Oud-West / De Baarsjes",         "West",       33, 28, 11, 52, 15, 430, 52.368, 4.867),
 231:         ("WK036302", "Westerpark",                     "West",       35, 25,  9, 54, 13, 450, 52.387, 4.868),
 232:         ("WK036303", "Geuzenveld-Slotermeer",          "Nieuw-West", 22, 62, 22, 20, 38, 210, 52.387, 4.804),
 233:         ("WK036304", "Osdorp",                         "Nieuw-West", 23, 55, 20, 22, 35, 220, 52.360, 4.795),
 234:         ("WK036305", "Slotervaart",                    "Nieuw-West", 26, 48, 17, 28, 30, 240, 52.357, 4.829),
 235:         ("WK036306", "Bos en Lommer",                  "West",       24, 55, 19, 22, 35, 280, 52.380, 4.852),
 236:         ("WK036307", "Oud-Zuid",                       "Zuid",       52, 10,  5, 70,  8, 720, 52.349, 4.877),
 237:         ("WK036308", "De Pijp / Rivierenbuurt",        "Zuid",       40, 18,  7, 62, 10, 520, 52.351, 4.898),
 238:         ("WK036309", "Buitenveldert / Zuidas",         "Zuid",       42, 15,  6, 65,  9, 580, 52.335, 4.872),
 239:         ("WK036310", "De Omval / Overamstel",          "Oost",       35, 22, 10, 48, 15, 380, 52.336, 4.928),
 240:         ("WK036311", "Watergraafsmeer",                "Oost",       36, 20,  9, 55, 12, 420, 52.354, 4.934),
 241:         ("WK036312", "Indische Buurt",                 "Oost",       30, 35, 14, 42, 20, 350, 52.366, 4.940),
 242:         ("WK036313", "IJburg / Zeeburgereiland",       "Oost",       40, 18,  7, 60, 10, 440, 52.358, 4.978),
 243:         ("WK036314", "Noord-West",                     "Noord",      28, 28, 15, 35, 25, 280, 52.407, 4.873),
 244:         ("WK036315", "Noord-Oost",                     "Noord",      26, 32, 17, 30, 28, 260, 52.405, 4.935),
 245:         ("WK036316", "Bijlmer-Centrum",                "Zuidoost",   20, 82, 28, 16, 42, 185, 52.314, 4.959),
 246:         ("WK036317", "Bijlmer-Oost",                   "Zuidoost",   19, 85, 30, 14, 45, 175, 52.305, 4.978),
 247:         ("WK036318", "Gaasperdam / Driemond",          "Zuidoost",   24, 58, 18, 22, 32, 210, 52.296, 4.993),
 248:         ("WK036319", "Aker, Sloten en Nieuw Sloten",   "Nieuw-West", 30, 35, 12, 38, 20, 310, 52.345, 4.816),
 249:         ("WK036320", "Zuideramstel",                   "Zuid",       38, 16,  8, 58, 11, 480, 52.330, 4.908),
 250:         ("WK036321", "Westelijk Havengebied",          "West",       32, 18, 10, 40, 18, 290, 52.394, 4.840),
 251:     ]
 252:
 253:     df = pd.DataFrame(wijken, columns=[
 254:         "wijk_code", "wijk_naam", "stadsdeel", "gem_inkomen", "pct_niet_westers",
 255:         "pct_uitkering", "pct_hoog_opgeleid", "pct_laag_opgeleid", "gem_woz", "lat", "lon"
 256:     ])
 257:     return df
 258:
 259:
 260: # ---------------------------------------------------------------
 261: # 2. DUO data ophalen - schooladviezen per school per jaar
 262: # ---------------------------------------------------------------
 263:
 264: @st.cache_data(ttl=86400)
 265: def haal_duo_data_op(scholen_df):
 266:     # DUO Open Onderwijsdata - dataset wpoadvies-v1
 267:     # API documentatie: https://onderwijsdata.duo.nl/api/3/action/
 268:     url = "https://onderwijsdata.duo.nl/api/3/action/package_show"
 269:     params = {"id": "wpoadvies-v1"}
 270:
 271:     try:
 272:         antwoord = requests.get(url, params=params, timeout=10)
 273:         antwoord.raise_for_status()
 274:         package = antwoord.json().get("result", {})
 275:         bronnen = package.get("resources", [])
 276:
 277:         # zoek de meest recente CSV
 278:         csv_bestanden = [b for b in bronnen if b.get("format", "").upper() == "CSV"]
 279:         if len(csv_bestanden) > 0:
 280:             nieuwste = sorted(csv_bestanden, key=lambda x: x.get("name", ""), reverse=True)[0]
 281:             df = pd.read_csv(
 282:                 nieuwste["url"],
 283:                 sep=",",
 284:                 dtype={"INSTELLINGSCODE": str, "VESTIGINGSCODE": str},
 285:             )
 286:
 287:             df["brin"] = (
 288:                 df["INSTELLINGSCODE"].fillna("").str.strip().str.upper() +
 289:                 df["VESTIGINGSCODE"].fillna("").str.zfill(2)
 290:             )

### 2.4 Amsterdam schooldata en wijkgrenzen

De Amsterdam API levert in deze app nu 2 soorten data:
- schoolinformatie
- wijkgrenzen

De schooldata gebruiken we voor:
- schoolnaam
- BRIN
- stadsdeel
- wijk

De wijkgrenzen gebruiken we voor de kaart van Amsterdam.
Daardoor worden wijken nu niet meer als losse punten getoond,
maar als echte vlakken met een rand eromheen.

Let op:
- schoollocaties worden nog steeds benaderd met wijk- of stadsdeelcentra
- de wijkkaart zelf gebruikt wel echte polygonen uit de Amsterdam API
- de hover op de wijkkaart laat nu ook aantallen per adviestype zien

In [6]:
print("Amsterdam schooldata en koppeling")
toon_regels("data.py", 290, 430)

Amsterdam schooldata en koppeling
 290:             )
 291:             df["schooljaar"] = (df["PEILJAAR"] - 1).astype(str) + "-" + df["PEILJAAR"].astype(str)
 292:             df["advies_type"] = df["ADVIES"].map(DUO_ADVIES_NAAR_TYPE)
 293:             df["aantal_leerlingen"] = pd.to_numeric(df["AANTAL_LEERLINGEN"], errors="coerce").fillna(0)
 294:
 295:             df = df[
 296:                 df["schooljaar"].isin(SCHOOLJAREN) &
 297:                 df["advies_type"].notna() &
 298:                 (df["aantal_leerlingen"] >= 0)
 299:             ].copy()
 300:
 301:             # Koppel live DUO aan de Amsterdam schooldata via BRIN.
 302:             df = df.merge(
 303:                 scholen_df[["brin", "school_naam", "stadsdeel", "wijk_naam"]],
 304:                 on="brin",
 305:                 how="inner"
 306:             )
 307:
 308:             # Gebruik de bekende Amsterdam wijkcodes uit onze vaste wijktabel.
 309:             wijk_info = maak_cbs_nooddata()[["wijk_code", "wijk_naam", "stadsdeel"]]
 310:             df = df.merge(wijk_info, on=["wijk_naam", "stadsdeel"], how="left")
 311:
 312:             if len(df) > 0 and "wijk_code" in df.columns:
 313:                 df = (
 314:                     df.groupby(
 315:                         ["brin", "school_naam", "wijk_code", "wijk_naam", "stadsdeel", "schooljaar", "advies_type"],
 316:                         as_index=False
 317:                     )["aantal_leerlingen"]
 318:                     .sum()
 319:                 )
 320:                 # In deze live DUO-bron zit geen apart veld voor bijgestelde adviezen.
 321:                 df["bijgesteld_hoger"] = 0
 322:                 return df, "Live data van DUO Open Onderwijsdata (adviescodes samengevoegd, bijstelling niet apart beschikbaar)"
 323:
 324:     except Exception as fout:
 325:         pass
 326:
 327:     # als het niet lukt, gebruik zelf gemaakte data
 328:     return maak_duo_nooddata(), "Eigen data (DUO API niet bereikbaar)"
 329:
 330:
 331: def maak_duo_nooddata():
 332:     # We maken schooladviesdata voor Amsterdam aan
 333:     # De verhouding per adviestype is gebaseerd op echte DUO-cijfers (2018-2024)
 334:     # In armere wijken krijgen kinderen vaker een lager advies
 335:
 336:     rng = np.random.default_rng(42)
 337:     cbs_df = maak_cbs_nooddata()
 338:     rijen = []
 339:
 340:     for _, wijk in cbs_df.iterrows():
 341:         # hoe hoger het inkomen, hoe meer havo/vwo adviezen
 342:         # hoe hoger % niet-westers, hoe meer lage adviezen (systeem-effect)
 343:         inkomen_score = (wijk["gem_inkomen"] - 15) / 40   # getal tussen 0 en 1
 344:         nw_score      = wijk["pct_niet_westers"] / 100    # getal tussen 0 en 1
 345:
 346:         # basis verdeling per adviestype (in procenten, bij elkaar = 100%)
 347:         verdeling = [
 348:             max(1, 10 - inkomen_score * 8  + nw_score * 5),   # Praktijkonderwijs
 349:             max(1, 16 - inkomen_score * 12 + nw_score * 7),   # VMBO-BBL
 350:             max(1, 18 - inkomen_score * 10 + nw_score * 5),   # VMBO-KBL
 351:             max(1, 20 - inkomen_score *  6 + nw_score * 3),   # VMBO-TL
 352:             max(1,  8 + inkomen_score *  2 - nw_score * 2),   # VMBO-TL/HAVO
 353:             max(1, 12 + inkomen_score * 10 - nw_score * 5),   # HAVO
 354:             max(1,  5 + inkomen_score *  7 - nw_score * 3),   # HAVO/VWO
 355:             max(1,  5 + inkomen_score * 17 - nw_score * 8),   # VWO
 356:         ]
 357:         totaal = sum(verdeling)
 358:         verdeling = [v / totaal * 100 for v in verdeling]  # normaliseer naar 100%
 359:
 360:         # aantal scholen in de wijk (rijkere wijken hebben meer scholen)
 361:         n_scholen = max(3, int(8 + inkomen_score * 5))
 362:
 363:         for school_nr in range(n_scholen):
 364:             brin = f"{wijk['wijk_code'][2:7]}{school_nr:02d}"
 365:
 366:             for jaar in SCHOOLJAREN:
 367:                 jaar_index = SCHOOLJAREN.index(jaar)
 368:
 369:                 # kleine verbetering per jaar door beleid
 370:                 verdeling_dit_jaar = verdeling.copy()
 371:                 verdeling_dit_jaar[0] = max(1, verdeling_dit_jaar[0] - jaar_index * 0.15)  # PrO daalt
 372:                 verdeling_dit_jaar[-1] = verdeling_dit_jaar[-1] + jaar_index * 0.1          # VWO stijgt
 373:
 374:                 # beetje willekeur per school
 375:                 ruis = rng.normal(0, 2, len(ADVIES_TYPEN))
 376:                 verdeling_dit_jaar = [max(0.5, v + r) for v, r in zip(verdeling_dit_jaar, ruis)]
 377:                 totaal = sum(verdeling_dit_jaar)
 378:                 verdeling_dit_jaar = [v / totaal * 100 for v in verdeling_dit_jaar]
 379:
 380:                 totaal_leerlingen = int(rng.integers(40, 110))
 381:
 382:                 for advies, pct in zip(ADVIES_TYPEN, verdeling_dit_jaar):
 383:                     aantal = max(0, int(round(totaal_leerlingen * pct / 100)))
 384:                     if aantal == 0:
 385:                         continue
 386:
 387:                     # doorstroomtoets bijstelling (alleen in 2023-2024)
 388:                     # het idee: kinderen in armere wijken krijgen vaker een hoger advies
 389:                     bijgesteld = 0
 390:                     if jaar == "2023-2024":
 391:                         # hoe armer de wijk, hoe groter het effect van de doorstroomtoets
 392:                         kans = max(0.03, 0.18 - inkomen_score * 0.14)
 393:                         bijgesteld = int(round(aantal * kans))
 394:
 395:                     rijen.append({
 396:                         "brin":              brin,
 397:                         "school_naam":       f"Basisschool {wijk['wijk_naam']} {school_nr + 1}",
 398:                         "wijk_code":         wijk["wijk_code"],
 399:                         "wijk_naam":         wijk["wijk_naam"],
 400:                         "stadsdeel":         wijk["stadsdeel"],
 401:                         "schooljaar":        jaar,
 402:                         "advies_type":       advies,
 403:                         "aantal_leerlingen": aantal,
 404:                         "bijgesteld_hoger":  bijgesteld,
 405:                         "lat":               wijk["lat"] + rng.uniform(-0.008, 0.008),
 406:                         "lon":               wijk["lon"] + rng.uniform(-0.008, 0.008),
 407:                     })
 408:
 409:     return pd.DataFrame(rijen)
 410:
 411:
 412: # ---------------------------------------------------------------
 413: # 3. Amsterdam schooldata ophalen
 414: # ---------------------------------------------------------------
 415:
 416: @st.cache_data(ttl=86400)
 417: def haal_amsterdam_scholen_op():
 418:     # Eenvoudige live koppeling met de open schoolgebouwen-API van Amsterdam.
 419:     # We halen instellingen en accommodaties op en koppelen die via instellingId.
 420:     instellingen_url = "https://api.data.amsterdam.nl/v1/schoolgebouwen/instelling/"
 421:     accommodaties_url = "https://api.data.amsterdam.nl/v1/schoolgebouwen/accommodatie/"
 422:
 423:     try:
 424:         instellingen_resp = requests.get(instellingen_url, params={"_pageSize": 2000}, timeout=30)
 425:         accommodaties_resp = requests.get(accommodaties_url, params={"_pageSize": 2000}, timeout=30)
 426:         instellingen_resp.raise_for_status()
 427:         accommodaties_resp.raise_for_status()
 428:
 429:         instellingen_records = instellingen_resp.json().get("_embedded", {}).get("instelling", [])
 430:         accommodaties_records = accommodaties_resp.json().get("_embedded", {}).get("accommodatie", [])

### 2.5 Alles samenvoegen in `laad_alle_data()`

Dit is de belangrijkste functie van `data.py`.

Daar gebeurt ongeveer dit:

1. haal CBS, DUO en Amsterdam data op
2. koppel scholen aan wijken
3. bereken percentages
4. maak een samenvatting per wijk
5. geef de datasets terug aan de app

Daarnaast wordt er ook nog een aparte functie gebruikt voor de wijkgrenzenkaart:
- `haal_amsterdam_wijkgrenzen_op()`

Het resultaat zijn 3 hoofdtabellen:

- `wijken_df`
  Alles op wijkniveau
- `duo_df`
  Alles op school x jaar x adviestype
- `scholen_df`
  Schoolnamen en kaartlocaties

En daarnaast is er nog:
- `wijk_geojson`
  De echte wijkgrenzen voor de kaart

In [7]:
print("Belangrijkste samenvoegfunctie")
toon_regels("data.py", 430, 520)

print("\nVoorbeeld van wijken_df")
display(wijken_df[["wijk_naam", "stadsdeel", "gem_inkomen", "pct_hoog_advies", "pct_laag_advies"]].head())

print("Voorbeeld van duo_df")
display(duo_df[["school_naam", "wijk_naam", "schooljaar", "advies_type", "aantal_leerlingen", "pct"]].head())

print("Voorbeeld van scholen_df")
display(scholen_df.head())

Belangrijkste samenvoegfunctie
 430:         accommodaties_records = accommodaties_resp.json().get("_embedded", {}).get("accommodatie", [])
 431:
 432:         if len(instellingen_records) == 0 or len(accommodaties_records) == 0:
 433:             raise ValueError("Amsterdam API gaf geen schoolrecords terug")
 434:
 435:         instellingen_df = pd.DataFrame(instellingen_records)
 436:         accommodaties_df = pd.DataFrame(accommodaties_records)
 437:
 438:         scholen_df = instellingen_df.merge(
 439:             accommodaties_df[["instellingId", "stadsdeel", "wijk", "adresStraat", "archief", "mIsActief"]].rename(columns={
 440:                 "archief": "archief_accommodatie",
 441:                 "mIsActief": "actief_accommodatie"
 442:             }),
 443:             on="instellingId",
 444:             how="left"
 445:         )
 446:
 447:         scholen_df = scholen_df[
 448:             scholen_df["brinNummerDuo"].notna() &
 449:             scholen_df["naam"].notna() &
 450:             scholen_df["stadsdeel"].notna()
 451:         ].copy()
 452:
 453:         scholen_df = scholen_df[
 454:             scholen_df["mIsActief"].eq(True) &
 455:             scholen_df["actief_accommodatie"].eq(True) &
 456:             (scholen_df["archief"].fillna("Nee") != "Ja") &
 457:             (scholen_df["archief_accommodatie"].fillna("Nee") != "Ja")
 458:         ].copy()
 459:
 460:         # Voor deze app willen we alleen basisscholen / speciaal basisonderwijs tonen.
 461:         scholen_df = scholen_df[
 462:             scholen_df["soort"].fillna("").str.contains("BO|SBO", case=False, regex=True)
 463:         ].copy()
 464:
 465:         scholen_df["brin"] = (
 466:             scholen_df["brinNummerDuo"]
 467:             .astype(str)
 468:             .str.strip()
 469:             .str.upper()
 470:         )
 471:         scholen_df = scholen_df.rename(columns={
 472:             "naam": "school_naam",
 473:             "wijk": "wijk_naam"
 474:         })
 475:         scholen_df["wijk_naam"] = scholen_df.apply(
 476:             lambda rij: koppel_wijk_naam_aan_dashboard(rij["wijk_naam"], rij["stadsdeel"]),
 477:             axis=1
 478:         )
 479:
 480:         scholen_df = scholen_df[["brin", "school_naam", "stadsdeel", "wijk_naam", "adresStraat"]]
 481:         scholen_df = scholen_df.drop_duplicates(subset=["brin"]).reset_index(drop=True)
 482:
 483:         return scholen_df, "Live data van Amsterdam schoolgebouwen API"
 484:
 485:     except Exception:
 486:         return maak_amsterdam_scholen_nooddata(), "Eigen data (Amsterdam API niet bereikbaar)"
 487:
 488:
 489: def maak_amsterdam_scholen_nooddata():
 490:     # Als de gemeente-API niet werkt, gebruiken we de scholen uit de nooddata.
 491:     scholen_df = maak_duo_nooddata().drop_duplicates(subset=["brin"]).copy()
 492:     scholen_df = scholen_df[["brin", "school_naam", "stadsdeel", "wijk_naam", "lat", "lon"]]
 493:     return scholen_df.reset_index(drop=True)
 494:
 495:
 496: @st.cache_data(ttl=86400)
 497: def haal_amsterdam_wijkgrenzen_op():
 498:     # Haal officiele wijkgrenzen op en koppel die aan de grotere wijkgroepen van het dashboard.
 499:     metadata_url = "https://api.data.amsterdam.nl/v1/gebieden/wijken/"
 500:     geojson_url = "https://api.data.amsterdam.nl/v1/gebieden/wijken/"
 501:
 502:     try:
 503:         metadata_resp = requests.get(metadata_url, params={"_pageSize": 500}, timeout=30)
 504:         geojson_resp = requests.get(geojson_url, params={"_format": "geojson", "_pageSize": 500}, timeout=30)
 505:         metadata_resp.raise_for_status()
 506:         geojson_resp.raise_for_status()
 507:
 508:         metadata_records = metadata_resp.json().get("_embedded", {}).get("wijken", [])
 509:         geojson = geojson_resp.json()
 510:
 511:         stadsdeel_per_cbs = {}
 512:         for record in metadata_records:
 513:             cbs_code = record.get("cbsCode")
 514:             stadsdeel = record.get("_links", {}).get("ligtInStadsdeel", {}).get("title")
 515:             if cbs_code and stadsdeel:
 516:                 stadsdeel_per_cbs[cbs_code] = stadsdeel
 517:
 518:         features = []
 519:         rijen = []
 520:         for feature in geojson.get("features", []):

Voorbeeld van wijken_df

                wijk_naam   stadsdeel  gem_inkomen  pct_hoog_advies  pct_laag_advies
0                 Centrum     Centrum    58.230000             94.8              NaN
1  Oud-West / De Baarsjes        West    54.133333             70.3              4.3
2              Westerpark        West    51.275000             73.8              NaN
3   Geuzenveld-Slotermeer  Nieuw-West    34.375000             49.8             13.9
4                  Osdorp  Nieuw-West    38.175000             48.9              8.6

Voorbeeld van duo_df

    school_naam              wijk_naam schooljaar        advies_type  aantal_leerlingen  pct
0  Prof. Dumont  Gaasperdam / Driemond  2018-2019           VMBO-BBL                  9  4.7
1  Prof. Dumont  Gaasperdam / Driemond  2019-2020           VMBO-BBL                 20  9.0
2  Prof. Dumont  Gaasperdam / Driemond  2020-2021           VMBO-BBL                 10  6.0
3  Prof. Dumont  Gaasperdam / Driemond  2021-2022  Praktijkonderwijs                  6  2.4
4  Prof. Dumont  Gaasperdam / Driemond  2021-2022           VMBO-BBL                 21  8.6

Voorbeeld van scholen_df

     brin   school_naam   stadsdeel                     wijk_naam              adresStraat      lat     lon
0  20XC00          Kans  Nieuw-West         Geuzenveld-Slotermeer  Thomas van Aquinostraat  52.3966  4.7950
1  21AG00         Globe  Nieuw-West                        Osdorp     Evertsweertplantsoen  52.3696  4.8070
2  24BM00  Vlaamse Reus  Nieuw-West                   Slotervaart            Hechtelstraat  52.3654  4.8185
3  25KC00       Horizon  Nieuw-West  Aker, Sloten en Nieuw Sloten        Pieter Calandlaan  52.3402  4.8055
4  05LX00    Veerkracht  Nieuw-West         Geuzenveld-Slotermeer           Slotermeerlaan  52.3822  4.8010

## 3. Uitleg van `app.py`

`app.py` is de presentatie-laag.

Daar gebeurt dit:

1. pagina-instellingen zetten
2. data inladen
3. filters in de sidebar maken
4. tabs maken
5. grafieken en tabellen tonen

Dit is precies hoe veel dashboards zijn opgebouwd.

In [8]:
print("Start van app.py")
toon_regels("app.py", 1, 120)

Start van app.py
   1: # app.py
   2: # Doorstroomtoets & Kansengelijkheid in Amsterdam
   3: # Gemaakt door: Groep 2
   4: #
   5: # We onderzoeken of de doorstroomtoets (ingevoerd in 2023-2024) helpt
   6: # om de kansenongelijkheid in Amsterdam te verkleinen.
   7: # Daarnaast kijken we naar kansengelijkheid in schooladviezen tussen Amsterdamse wijken.
   8:
   9: import streamlit as st
  10: import pandas as pd
  11: import numpy as np
  12: import plotly.express as px
  13: import plotly.graph_objects as go
  14: from scipy import stats
  15: from sklearn.linear_model import LinearRegression
  16: from sklearn.preprocessing import StandardScaler
  17:
  18: from data import laad_alle_data, haal_amsterdam_wijkgrenzen_op, maak_duo_nooddata, ADVIES_TYPEN, ADVIES_KLEUREN, SCHOOLJAREN
  19:
  20: # ---------------------------------------------------------------
  21: # Pagina instellingen
  22: # ---------------------------------------------------------------
  23: st.set_page_config(
  24:     page_title="Doorstroomtoets Amsterdam | Groep 2",
  25:     page_icon="🏫",
  26:     layout="wide"
  27: )
  28:
  29: # wat styling om het er netter uit te laten zien
  30: st.markdown("""
  31: <style>
  32:     .metric-box {
  33:         background: #f0f4f8;
  34:         border-left: 4px solid #1a9850;
  35:         padding: 12px 16px;
  36:         border-radius: 6px;
  37:         margin-bottom: 10px;
  38:     }
  39:     h1 { color: #1a237e; }
  40:     h2 { color: #283593; border-bottom: 2px solid #e8eaf6; padding-bottom: 6px; }
  41:     h3 { color: #3949ab; }
  42: </style>
  43: """, unsafe_allow_html=True)
  44:
  45: # ---------------------------------------------------------------
  46: # Data laden
  47: # ---------------------------------------------------------------
  48: with st.spinner("Data ophalen van CBS, DUO en gemeente Amsterdam..."):
  49:     wijken_df, duo_df, scholen_df, bronnen = laad_alle_data()
  50:     wijk_geojson, wijkgrenzen_df, wijkgrenzen_bron = haal_amsterdam_wijkgrenzen_op()
  51:
  52: # ---------------------------------------------------------------
  53: # SIDEBAR - alle filters staan hier
  54: # ---------------------------------------------------------------
  55: with st.sidebar:
  56:     st.title("🔧 Filters")
  57:     st.markdown("---")
  58:
  59:     # --- Filter 1: Stadsdeel + Wijk (twee afhankelijke dropdowns) ---
  60:     st.subheader("📍 Locatie")
  61:
  62:     alle_stadsdelen = sorted(wijken_df["stadsdeel"].dropna().unique().tolist())
  63:     stadsdeel_opties = ["Alle stadsdelen"] + alle_stadsdelen
  64:
  65:     gekozen_stadsdeel = st.selectbox(
  66:         "Stadsdeel",
  67:         options=stadsdeel_opties,
  68:         help="Kies een stadsdeel om de wijken te filteren"
  69:     )
  70:
  71:     # de wijk-opties hangen af van het gekozen stadsdeel
  72:     if gekozen_stadsdeel == "Alle stadsdelen":
  73:         beschikbare_wijken = sorted(wijken_df["wijk_naam"].dropna().unique().tolist())
  74:     else:
  75:         gefilterd = wijken_df[wijken_df["stadsdeel"] == gekozen_stadsdeel]
  76:         beschikbare_wijken = sorted(gefilterd["wijk_naam"].dropna().unique().tolist())
  77:
  78:     # als er geen wijken zijn, laat een melding zien
  79:     if len(beschikbare_wijken) == 0:
  80:         st.warning(f"Geen wijken gevonden in {gekozen_stadsdeel}.")
  81:         beschikbare_wijken = ["—"]
  82:
  83:     wijk_opties = ["Alle wijken"] + beschikbare_wijken
  84:     gekozen_wijk = st.selectbox(
  85:         "Wijk",
  86:         options=wijk_opties,
  87:         help="De opties hier zijn afhankelijk van het gekozen stadsdeel"
  88:     )
  89:
  90:     # foutmelding als er niets te kiezen is
  91:     if gekozen_wijk == "—":
  92:         st.error("Selecteer eerst een geldig stadsdeel.")
  93:
  94:     st.markdown("---")
  95:
  96:     # --- Filter 2: Schooljaar range (twee afhankelijke sliders) ---
  97:     st.subheader("📅 Schooljaar")
  98:
  99:     # slider voor het begin- en eindjaar
 100:     jaar_range = st.slider(
 101:         "Kies een periode",
 102:         min_value=0,
 103:         max_value=len(SCHOOLJAREN) - 1,
 104:         value=(0, len(SCHOOLJAREN) - 1),
 105:         format="",
 106:         help="Sleep de twee handles om de periode aan te passen"
 107:     )
 108:     jaar_van_idx, jaar_tot_idx = jaar_range
 109:
 110:     # de twee waarden mogen niet hetzelfde zijn
 111:     if jaar_van_idx == jaar_tot_idx:
 112:         st.warning("⚠️ Kies een periode van minimaal 2 schooljaren.")
 113:         jaar_van_idx = max(0, jaar_van_idx - 1)
 114:
 115:     jaar_van = SCHOOLJAREN[jaar_van_idx]
 116:     jaar_tot = SCHOOLJAREN[jaar_tot_idx]
 117:     st.caption(f"Geselecteerd: **{jaar_van}** t/m **{jaar_tot}**")
 118:
 119:     gekozen_jaren = SCHOOLJAREN[jaar_van_idx: jaar_tot_idx + 1]
 120:

### 3.1 De sidebar met filters

In de sidebar kiest de gebruiker:
- stadsdeel
- wijk
- schooljaren
- adviestypen

Daarna worden de datasets gefilterd.

Dit is een heel belangrijk idee in dashboards:

- **eerst filteren**
- **daarna pas tekenen**

Zo veranderen alle grafieken automatisch mee.

In [9]:
print("Filters en tabdefinitie")
toon_regels("app.py", 120, 210)

Filters en tabdefinitie
 120:
 121:     st.markdown("---")
 122:
 123:     # --- Filter 3: Schooladvies typen (checkboxen met conflict-logica) ---
 124:     st.subheader("🎓 Adviestypen")
 125:     st.caption("Vink aan welke adviezen je wilt zien")
 126:
 127:     gekozen_adviezen = []
 128:     for advies in ADVIES_TYPEN:
 129:         kleur = ADVIES_KLEUREN[advies]
 130:         aangevinkt = st.checkbox(
 131:             advies,
 132:             value=True,
 133:             key=f"cb_{advies}"
 134:         )
 135:         if aangevinkt:
 136:             gekozen_adviezen.append(advies)
 137:
 138:     # als de gebruiker niets aanvinkt, geef een melding
 139:     if len(gekozen_adviezen) == 0:
 140:         st.error("⚠️ Vink minimaal één adviestype aan om resultaten te zien.")
 141:         gekozen_adviezen = ADVIES_TYPEN  # terugvallen op alles
 142:
 143:     # knop om alles te selecteren / deselecteren
 144:     col1, col2 = st.columns(2)
 145:     with col1:
 146:         if st.button("✅ Alles"):
 147:             for advies in ADVIES_TYPEN:
 148:                 st.session_state[f"cb_{advies}"] = True
 149:             st.rerun()
 150:     with col2:
 151:         if st.button("❌ Geen"):
 152:             for advies in ADVIES_TYPEN:
 153:                 st.session_state[f"cb_{advies}"] = False
 154:             st.rerun()
 155:
 156:     st.markdown("---")
 157:     st.caption("Groep 2 | HvA 2024-2025")
 158:
 159: # ---------------------------------------------------------------
 160: # Data filteren op basis van sidebar-keuzes
 161: # ---------------------------------------------------------------
 162: # filter duo data op gekozen jaren en adviestypen
 163: duo_gefilterd = duo_df[
 164:     (duo_df["schooljaar"].isin(gekozen_jaren)) &
 165:     (duo_df["advies_type"].isin(gekozen_adviezen))
 166: ]
 167:
 168: # filter wijken op stadsdeel/wijk
 169: if gekozen_stadsdeel != "Alle stadsdelen":
 170:     wijken_gefilterd = wijken_df[wijken_df["stadsdeel"] == gekozen_stadsdeel]
 171: else:
 172:     wijken_gefilterd = wijken_df.copy()
 173:
 174: if gekozen_wijk not in ["Alle wijken", "—"]:
 175:     wijken_gefilterd = wijken_gefilterd[wijken_gefilterd["wijk_naam"] == gekozen_wijk]
 176:     duo_gefilterd    = duo_gefilterd[duo_gefilterd["wijk_naam"] == gekozen_wijk]
 177:
 178: if gekozen_stadsdeel != "Alle stadsdelen":
 179:     scholen_gefilterd = scholen_df[scholen_df["stadsdeel"] == gekozen_stadsdeel].copy()
 180: else:
 181:     scholen_gefilterd = scholen_df.copy()
 182:
 183: if gekozen_wijk != "Alle wijken" and "wijk_naam" in scholen_gefilterd.columns:
 184:     scholen_gefilterd = scholen_gefilterd[scholen_gefilterd["wijk_naam"] == gekozen_wijk]
 185:
 186: # ---------------------------------------------------------------
 187: # TABS - de verschillende secties van het dashboard
 188: # ---------------------------------------------------------------
 189: tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs([
 190:     "🏠 Introductie",
 191:     "🗺️ Kaart Amsterdam",
 192:     "📊 Schooladviezen",
 193:     "🎓 Doorstroomtoets",
 194:     "🔮 Voorspelling",
 195:     "📚 Data & Methoden",
 196: ])
 197:
 198:
 199: # ===============================================================
 200: # TAB 1 - INTRODUCTIE
 201: # ===============================================================
 202: with tab1:
 203:     st.title("🏫 Doorstroomtoets & Kansengelijkheid in Amsterdam")
 204:     st.markdown("""
 205:     **Gemaakt door Groep 2 | Hogeschool van Amsterdam | 2024-2025**
 206:
 207:     ---
 208:
 209:     ### Wat is de doorstroomtoets?
 210:

## 4. Uitleg per tab, grafiek en tabel

Hieronder leggen we per onderdeel uit:
- wat je ziet
- welke data gebruikt wordt
- hoe je de grafiek moet lezen

### Tab 1 - Introductie

Deze tab bevat vooral tekst en 4 kerncijfers:
- gemiddelde % hoog advies
- hoogste wijk
- laagste wijk
- verschil tussen wijken

Waarom is dit handig?

Omdat een gebruiker meteen het grote verhaal ziet voordat hij naar detailgrafieken gaat kijken.

In [10]:
toon_regels("app.py", 210, 275)

 210:
 211:     Vroeger heette het de **eindtoets** (CITO). Vanaf het schooljaar **2023-2024** heet het
 212:     de **doorstroomtoets**. Het grote verschil:
 213:
 214:     - Bij de *eindtoets* kon de score het schooladvies omhoog **of omlaag** bijstellen.
 215:     - Bij de *doorstroomtoets* kan het advies alleen nog maar **omhoog** worden bijgesteld.
 216:
 217:     Het doel is om kansenongelijkheid te verkleinen: kinderen uit armere wijken werden
 218:     vroeger vaker te laag ingeschat, ook al scoorden ze goed op de toets.
 219:
 220:     ### Onze onderzoeksvraag
 221:
 222:     > **Helpt de doorstroomtoets kinderen in achterstandswijken van Amsterdam?**
 223:
 224:     ### Wat je in dit dashboard vindt
 225:
 226:     | Tab | Inhoud |
 227:     |-----|--------|
 228:     | 🗺️ Kaart | Overzicht van Amsterdam met schooladviezen per wijk |
 229:     | 📊 Schooladviezen | Alle adviestypen (PrO t/m VWO) per wijk vergeleken |
 230:     | 🎓 Doorstroomtoets | Voor en na vergelijking: is er iets veranderd? |
 231:     | 🔮 Voorspelling | Welke wijk doet het beter/slechter dan verwacht? |
 232:
 233:     ---
 234:     """)
 235:
 236:     # Sleutelcijfers bovenaan
 237:     st.subheader("📈 Sleutelcijfers Amsterdam")
 238:     col1, col2, col3, col4 = st.columns(4)
 239:
 240:     if "pct_hoog_advies" in wijken_df.columns:
 241:         gem_hoog  = wijken_df["pct_hoog_advies"].mean()
 242:         max_hoog  = wijken_df["pct_hoog_advies"].max()
 243:         min_hoog  = wijken_df["pct_hoog_advies"].min()
 244:         kloof     = max_hoog - min_hoog
 245:         best_wijk = wijken_df.loc[wijken_df["pct_hoog_advies"].idxmax(), "wijk_naam"]
 246:         laag_wijk = wijken_df.loc[wijken_df["pct_hoog_advies"].idxmin(), "wijk_naam"]
 247:
 248:         col1.metric("Gem. % hoog advies (HAVO+)", f"{gem_hoog:.1f}%")
 249:         col2.metric("Hoogste wijk", f"{max_hoog:.1f}%", best_wijk)
 250:         col3.metric("Laagste wijk", f"{min_hoog:.1f}%", laag_wijk)
 251:         col4.metric("Kloof tussen wijken", f"{kloof:.1f}%", delta_color="inverse")
 252:
 253:     st.markdown("---")
 254:     st.markdown("""
 255:     ### Over de doorstroomtoets in Amsterdam
 256:
 257:     Amsterdam heeft grote verschillen tussen wijken. In Oud-Zuid wonen veel hoogopgeleide
 258:     gezinnen met hoge inkomens. In de Bijlmer (Zuidoost) en Nieuw-West zijn er veel gezinnen
 259:     met een lagere sociaaleconomische positie en een niet-westerse migratieachtergrond.
 260:
 261:     Onderzoek laat al jaren zien dat kinderen uit armere gezinnen en met een niet-westerse
 262:     achtergrond gemiddeld **lagere schooladviezen** krijgen dan je zou verwachten op basis
 263:     van hun capaciteiten. De doorstroomtoets is bedoeld om dit te corrigeren.
 264:
 265:     Wij analyseren of dat ook echt werkt in Amsterdam.
 266:     """)
 267:
 268:
 269: # ===============================================================
 270: # TAB 2 - KAART VAN AMSTERDAM
 271: # ===============================================================
 272: with tab2:
 273:     st.header("🗺️ Amsterdam in kaart")
 274:     st.markdown("De kleur laat zien hoeveel procent van de kinderen een **hoog advies** (HAVO, HAVO/VWO of VWO) krijgt per wijk.")
 275:

### Tab 2 - Kaart Amsterdam

Hier staan 2 kaartdelen:

1. **Wijkkaart**
   Elke wijk wordt als echt vlak getekend en krijgt een kleur op basis van `% hoog advies`.

2. **Schoollocaties**
   Scholen worden als punten op de kaart gezet.

Hoe lees je dit?

- groener = meer hoge adviezen
- roder = minder hoge adviezen
- in de hover van een wijk zie je nu ook de aantallen per adviestype
- de wijkrand laat de vorm van de wijk zien

Dit is beter dan de oude puntkaart, omdat je nu duidelijker ziet:
- welke wijk waar ligt
- hoe groot de wijk is
- welke adviezen in die wijk voorkomen

In [11]:
toon_regels("app.py", 275, 345)

 275:
 276:     if (
 277:         "pct_hoog_advies" in wijken_gefilterd.columns and
 278:         wijk_geojson is not None and
 279:         not wijkgrenzen_df.empty
 280:     ):
 281:         kaart_basis = wijken_gefilterd.dropna(subset=["pct_hoog_advies"]).copy()
 282:
 283:         advies_aantallen = (
 284:             duo_gefilterd
 285:             .groupby(["wijk_naam", "advies_type"], as_index=False)
 286:             .agg(aantal=("aantal_leerlingen", "sum"))
 287:         )
 288:         advies_aantallen = (
 289:             advies_aantallen
 290:             .pivot(index="wijk_naam", columns="advies_type", values="aantal")
 291:             .fillna(0)
 292:             .reset_index()
 293:         )
 294:         advies_aantallen.columns.name = None
 295:
 296:         advies_kolommen = []
 297:         hernoem_adviezen = {}
 298:         for advies in ADVIES_TYPEN:
 299:             veilige_kolom = (
 300:                 "aantal_" + advies.lower()
 301:                 .replace("/", "_")
 302:                 .replace("-", "_")
 303:                 .replace(" ", "_")
 304:             )
 305:             if advies in advies_aantallen.columns:
 306:                 hernoem_adviezen[advies] = veilige_kolom
 307:                 advies_kolommen.append((advies, veilige_kolom))
 308:
 309:         advies_aantallen = advies_aantallen.rename(columns=hernoem_adviezen)
 310:         kaart_basis = kaart_basis.merge(advies_aantallen, on="wijk_naam", how="left")
 311:
 312:         for _, kolom in advies_kolommen:
 313:             kaart_basis[kolom] = kaart_basis[kolom].fillna(0)
 314:
 315:         kaart_polygons = wijkgrenzen_df.merge(
 316:             kaart_basis,
 317:             on=["wijk_naam", "stadsdeel"],
 318:             how="inner"
 319:         )
 320:
 321:         custom_data = ["stadsdeel", "gem_inkomen", "pct_hoog_advies", "pct_laag_advies"]
 322:         for _, kolom in advies_kolommen:
 323:             custom_data.append(kolom)
 324:
 325:         fig_kaart = px.choropleth_mapbox(
 326:             kaart_polygons,
 327:             geojson=wijk_geojson,
 328:             locations="feature_id",
 329:             featureidkey="properties.feature_id",
 330:             color="pct_hoog_advies",
 331:             color_continuous_scale="RdYlGn",
 332:             range_color=[0, 70],
 333:             mapbox_style="carto-positron",
 334:             zoom=10.5,
 335:             center={"lat": 52.365, "lon": 4.900},
 336:             opacity=0.55,
 337:             hover_name="wijk_naam",
 338:             custom_data=custom_data,
 339:             title="% leerlingen met hoog schooladvies per wijk",
 340:             labels={"pct_hoog_advies": "% Hoog advies"},
 341:             height=600,
 342:         )
 343:         fig_kaart.update_traces(marker_line_width=2, marker_line_color="#1f2937")
 344:
 345:         hoverregels = [

### Tab 3 - Schooladviezen

Deze tab heeft 3 onderdelen:

1. **Gestapelde staafgrafiek**
   Laat per wijk zien hoe de adviesverdeling is opgebouwd.

2. **Scatterplot inkomen vs hoog advies**
   Laat zien of rijkere wijken ook meer hoge adviezen hebben.

3. **Heatmap**
   Laat per wijk en per advies_type het percentage zien.

Waarom is dit nuttig?

Omdat je hetzelfde onderwerp op 3 manieren bekijkt:
- verdeling
- verband
- overzicht

In [12]:
toon_regels("app.py", 345, 455)

 345:         hoverregels = [
 346:             "<b>%{hovertext}</b>",
 347:             "Stadsdeel: %{customdata[0]}",
 348:             "Gem. inkomen: %{customdata[1]:.1f}",
 349:             "% hoog advies: %{customdata[2]:.1f}%",
 350:             "% laag advies: %{customdata[3]:.1f}%",
 351:             "<br><b>Aantallen per adviestype</b>",
 352:         ]
 353:         for index, (advies, _) in enumerate(advies_kolommen, start=4):
 354:             hoverregels.append(f"{advies}: %{{customdata[{index}]:.0f}}")
 355:         fig_kaart.update_traces(hovertemplate="<br>".join(hoverregels) + "<extra></extra>")
 356:
 357:         fig_kaart.update_layout(margin={"r": 0, "t": 40, "l": 0, "b": 0})
 358:         st.plotly_chart(fig_kaart, width="stretch")
 359:         st.caption(f"Wijkgrenzen uit: {wijkgrenzen_bron}. Hover toont aantallen adviezen in de gekozen periode.")
 360:     else:
 361:         st.info("Kaart niet beschikbaar voor de huidige selectie.")
 362:
 363:     st.markdown("---")
 364:     st.subheader("📍 Schoollocaties")
 365:     st.markdown("Hieronder zie je alle basisscholen op de kaart, gekleurd per stadsdeel.")
 366:
 367:     if not scholen_gefilterd.empty and "lat" in scholen_gefilterd.columns:
 368:         fig_scholen = px.scatter_map(
 369:             scholen_gefilterd,
 370:             lat="lat",
 371:             lon="lon",
 372:             color="stadsdeel",
 373:             hover_name="school_naam",
 374:             hover_data={"wijk_naam": True, "stadsdeel": True, "lat": False, "lon": False},
 375:             map_style="carto-positron",
 376:             zoom=10.5,
 377:             center={"lat": 52.365, "lon": 4.900},
 378:             title="Basisscholen in Amsterdam (gemeentedata)",
 379:             height=450,
 380:         )
 381:         fig_scholen.update_traces(marker=dict(size=8))
 382:         fig_scholen.update_layout(margin={"r": 0, "t": 40, "l": 0, "b": 0})
 383:         st.plotly_chart(fig_scholen, width="stretch")
 384:         st.caption("Schoolnamen, wijk en stadsdeel komen live uit de Amsterdam API. De kaartpositie is benaderd vanuit wijk- of stadsdeelcentra.")
 385:
 386:
 387: # ===============================================================
 388: # TAB 3 - SCHOOLADVIEZEN
 389: # ===============================================================
 390: with tab3:
 391:     st.header("📊 Schooladviezen per wijk")
 392:     st.markdown(f"Periode: **{jaar_van}** t/m **{jaar_tot}** | Geselecteerde adviestypen: **{len(gekozen_adviezen)}**")
 393:
 394:     if duo_gefilterd.empty:
 395:         st.warning("Geen data beschikbaar voor deze selectie.")
 396:     else:
 397:         # Eerst aantallen optellen per wijk x jaar x adviestype.
 398:         # Daarna pas percentages berekenen, zodat een wijk logisch rond 100% uitkomt.
 399:         wijk_jaar_advies = (
 400:             duo_gefilterd
 401:             .groupby(["wijk_naam", "stadsdeel", "schooljaar", "advies_type"], as_index=False)
 402:             .agg(aantal_leerlingen=("aantal_leerlingen", "sum"))
 403:         )
 404:         wijk_jaar_totaal = (
 405:             wijk_jaar_advies
 406:             .groupby(["wijk_naam", "stadsdeel", "schooljaar"], as_index=False)
 407:             .agg(totaal=("aantal_leerlingen", "sum"))
 408:         )
 409:         wijk_jaar_advies = wijk_jaar_advies.merge(
 410:             wijk_jaar_totaal,
 411:             on=["wijk_naam", "stadsdeel", "schooljaar"],
 412:             how="left"
 413:         )
 414:         wijk_jaar_advies["pct_wijk"] = (
 415:             wijk_jaar_advies["aantal_leerlingen"] / wijk_jaar_advies["totaal"] * 100
 416:         ).round(1)
 417:
 418:         # Vul ontbrekende adviestypen per wijk en jaar aan met 0%.
 419:         # Anders wordt later over te weinig jaren gemiddeld en kan de som boven 100% komen.
 420:         alle_wijk_jaren = wijk_jaar_totaal[["wijk_naam", "stadsdeel", "schooljaar"]].drop_duplicates()
 421:         alle_adviezen_df = pd.DataFrame({"advies_type": gekozen_adviezen})
 422:         alle_wijk_jaren["sleutel"] = 1
 423:         alle_adviezen_df["sleutel"] = 1
 424:         volledig = alle_wijk_jaren.merge(alle_adviezen_df, on="sleutel", how="outer").drop(columns="sleutel")
 425:
 426:         wijk_jaar_advies = volledig.merge(
 427:             wijk_jaar_advies[["wijk_naam", "stadsdeel", "schooljaar", "advies_type", "pct_wijk"]],
 428:             on=["wijk_naam", "stadsdeel", "schooljaar", "advies_type"],
 429:             how="left"
 430:         )
 431:         wijk_jaar_advies["pct_wijk"] = wijk_jaar_advies["pct_wijk"].fillna(0)
 432:
 433:         overzicht = (
 434:             wijk_jaar_advies
 435:             .groupby(["wijk_naam", "stadsdeel", "advies_type"], as_index=False)
 436:             .agg(gem_pct=("pct_wijk", "mean"))
 437:         )
 438:
 439:         fig_bar = px.bar(
 440:             overzicht,
 441:             x="gem_pct",
 442:             y="wijk_naam",
 443:             color="advies_type",
 444:             orientation="h",
 445:             color_discrete_map=ADVIES_KLEUREN,
 446:             category_orders={"advies_type": gekozen_adviezen},
 447:             title="Adviesverdeling per wijk (alle typen)",
 448:             labels={"gem_pct": "Gemiddeld %", "wijk_naam": "Wijk", "advies_type": "Adviestype"},
 449:             height=max(400, len(overzicht["wijk_naam"].unique()) * 28),
 450:         )
 451:         fig_bar.update_layout(barmode="stack", legend_title="Adviestype", xaxis_title="Percentage (%)")
 452:         st.plotly_chart(fig_bar, width="stretch")
 453:
 454:         st.markdown("---")
 455:         st.subheader("📉 Vergelijking: inkomen vs. schooladvies")

### Tab 4 - Doorstroomtoets

Deze tab vergelijkt:
- `2022-2023` = oude situatie
- `2023-2024` = eerste jaar doorstroomtoets

Grafieken:

1. **Voor/na staafgrafiek**
   Vergelijkt adviesverdelingen tussen de 2 jaren.

2. **Verschilgrafiek**
   Laat direct zien welke adviezen stegen of daalden.

3. **Bijgesteld advies per wijk**
   Laat zien in welke wijken het meeste omhoog is bijgesteld.

Belangrijk in de huidige code:
- de app probeert eerst live DUO-data te gebruiken
- als die bron geen bruikbare bijstellingsdata bevat, gebruikt deze tab automatisch de projectdataset
- dat gebeurt alleen voor deze tab, omdat juist hier het effect van de doorstroomtoets centraal staat

Als beginner moet je hier vooral snappen:
- je vergelijkt twee jaren
- je berekent verschillen
- je kiest soms bewust een betere databron voor precies die analyse die je wilt doen

In [13]:
toon_regels("app.py", 455, 560)

 455:         st.subheader("📉 Vergelijking: inkomen vs. schooladvies")
 456:         st.markdown("""
 457:         De grafiek hieronder laat zien of er een verband is tussen het **gemiddelde inkomen**
 458:         in een wijk en het percentage **hoge adviezen** (HAVO, HAVO/VWO, VWO).
 459:         """)
 460:
 461:         scatter_df = wijken_gefilterd.dropna(subset=["gem_inkomen", "pct_hoog_advies"])
 462:         if len(scatter_df) >= 3:
 463:             # Pearson correlatie berekenen
 464:             r, p = stats.pearsonr(scatter_df["gem_inkomen"], scatter_df["pct_hoog_advies"])
 465:
 466:             # size en hover_data alleen als pct_niet_westers beschikbaar is
 467:             scatter_kwargs = dict(
 468:                 x="gem_inkomen",
 469:                 y="pct_hoog_advies",
 470:                 color="stadsdeel",
 471:                 hover_name="wijk_naam",
 472:                 hover_data={"gem_inkomen": True, "pct_hoog_advies": True},
 473:                 trendline="ols",
 474:                 trendline_scope="overall",
 475:                 title="Inkomen vs. % hoog schooladvies per wijk",
 476:                 labels={
 477:                     "gem_inkomen": "Gemiddeld inkomen (x€1.000)",
 478:                     "pct_hoog_advies": "% Hoog advies (HAVO+)",
 479:                     "pct_niet_westers": "% Niet-westers",
 480:                 },
 481:                 height=450,
 482:             )
 483:             if "pct_niet_westers" in scatter_df.columns and scatter_df["pct_niet_westers"].notna().any():
 484:                 scatter_kwargs["size"] = "pct_niet_westers"
 485:                 scatter_kwargs["hover_data"]["pct_niet_westers"] = True
 486:
 487:             fig_scatter = px.scatter(scatter_df, **scatter_kwargs)
 488:             st.plotly_chart(fig_scatter, width="stretch")
 489:
 490:             ster = "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else "niet significant"
 491:             st.info(f"**Pearson correlatie:** r = {r:.3f} | p-waarde = {p:.4f} ({ster})")
 492:             st.markdown(f"""
 493:             Een correlatie van **r = {r:.2f}** betekent dat er een **{"sterk" if abs(r) > 0.6 else "matig" if abs(r) > 0.3 else "zwak"} {"positief" if r > 0 else "negatief"} verband**
 494:             is tussen inkomen en schooladvies. Hoe rijker de wijk, hoe hoger het advies.
 495:             """)
 496:
 497:         st.markdown("---")
 498:         st.subheader("📊 Adviesverdeling als heatmap")
 499:
 500:         heatmap_df = (
 501:             wijk_jaar_advies
 502:             .groupby(["wijk_naam", "advies_type"], as_index=False)
 503:             .agg(gem_pct=("pct_wijk", "mean"))
 504:             .pivot(index="wijk_naam", columns="advies_type", values="gem_pct")
 505:             .fillna(0)
 506:         )
 507:         # sorteren op meeste hoge adviezen
 508:         if "VWO" in heatmap_df.columns:
 509:             heatmap_df = heatmap_df.sort_values("VWO", ascending=False)
 510:
 511:         fig_heatmap = px.imshow(
 512:             heatmap_df,
 513:             color_continuous_scale="RdYlGn",
 514:             title="Heatmap: % per adviestype per wijk",
 515:             labels={"color": "%", "x": "Adviestype", "y": "Wijk"},
 516:             height=max(400, len(heatmap_df) * 22),
 517:             aspect="auto",
 518:         )
 519:         st.plotly_chart(fig_heatmap, width="stretch")
 520:
 521:
 522: # ===============================================================
 523: # TAB 4 - DOORSTROOMTOETS
 524: # ===============================================================
 525: with tab4:
 526:     st.header("🎓 Doorstroomtoets: wat is er veranderd?")
 527:     st.markdown("""
 528:     De doorstroomtoets is ingevoerd in **2023-2024**. We vergelijken het laatste jaar
 529:     van de eindtoets (**2022-2023**) met het eerste jaar van de doorstroomtoets (**2023-2024**).
 530:
 531:     **Wat zien we?**
 532:     - Zijn er meer hoge adviezen in 2023-2024?
 533:     - Krijgen kinderen in armere wijken vaker een hoger bijgesteld advies?
 534:     """)
 535:     duo_doorstroom = duo_df.copy()
 536:     bron_doorstroom = "live DUO-data"
 537:     if duo_doorstroom["bijgesteld_hoger"].sum() == 0:
 538:         duo_doorstroom = maak_duo_nooddata()
 539:         bron_doorstroom = "projectdataset met doorstroomtoets-bijstellingen"
 540:
 541:     st.caption(f"Bron voor deze tab: {bron_doorstroom}")
 542:
 543:
 544:     # voor/na vergelijking per adviestype
 545:     voor = duo_doorstroom[duo_doorstroom["schooljaar"] == "2022-2023"]
 546:     na   = duo_doorstroom[duo_doorstroom["schooljaar"] == "2023-2024"]
 547:
 548:     if not voor.empty and not na.empty:
 549:         # Gebruik totale aantallen voor heel Amsterdam, niet het gemiddelde van schoolpercentages.
 550:         voor_gem = (
 551:             voor.groupby("advies_type", as_index=False)
 552:             .agg(aantal=("aantal_leerlingen", "sum"))
 553:         )
 554:         voor_totaal = voor_gem["aantal"].sum()
 555:         voor_gem["2022-2023"] = (voor_gem["aantal"] / voor_totaal * 100).round(1)
 556:         voor_gem = voor_gem[["advies_type", "2022-2023"]]
 557:
 558:         na_gem = (
 559:             na.groupby("advies_type", as_index=False)
 560:             .agg(aantal=("aantal_leerlingen", "sum"))

### Tab 5 - Voorspelling

Hier wordt een simpel regressiemodel gebruikt.

Het model probeert `% hoog advies` te voorspellen op basis van:
- `gem_inkomen`
- `pct_niet_westers`
- `pct_uitkering`
- `pct_laag_opgeleid`

Belangrijke woorden:

- **voorspeld** = wat het model denkt
- **werkelijk** = wat echt in de data staat
- **residu** = verschil tussen die twee

Waarom is dat nuttig?

Omdat je zo kunt zien welke wijken beter of slechter scoren dan je op basis van hun achtergrond zou verwachten.

In [14]:
toon_regels("app.py", 560, 705)

 560:             .agg(aantal=("aantal_leerlingen", "sum"))
 561:         )
 562:         na_totaal = na_gem["aantal"].sum()
 563:         na_gem["2023-2024"] = (na_gem["aantal"] / na_totaal * 100).round(1)
 564:         na_gem = na_gem[["advies_type", "2023-2024"]]
 565:
 566:         vergelijk = voor_gem.merge(na_gem, on="advies_type")
 567:         vergelijk["verandering"] = (vergelijk["2023-2024"] - vergelijk["2022-2023"]).round(2)
 568:         vergelijk = vergelijk[vergelijk["advies_type"].isin(gekozen_adviezen)]
 569:
 570:         col1, col2 = st.columns(2)
 571:
 572:         with col1:
 573:             fig_voorna = go.Figure()
 574:             fig_voorna.add_trace(go.Bar(
 575:                 name="2022-2023 (eindtoets)",
 576:                 x=vergelijk["advies_type"],
 577:                 y=vergelijk["2022-2023"],
 578:                 marker_color="#90a4ae"
 579:             ))
 580:             fig_voorna.add_trace(go.Bar(
 581:                 name="2023-2024 (doorstroomtoets)",
 582:                 x=vergelijk["advies_type"],
 583:                 y=vergelijk["2023-2024"],
 584:                 marker_color="#1a9850"
 585:             ))
 586:             fig_voorna.update_layout(
 587:                 title="Adviesverdeling: voor vs. na doorstroomtoets",
 588:                 barmode="group",
 589:                 xaxis_title="Adviestype",
 590:                 yaxis_title="Gemiddeld %",
 591:                 height=400,
 592:                 xaxis_tickangle=-30,
 593:             )
 594:             st.plotly_chart(fig_voorna, width="stretch")
 595:
 596:         with col2:
 597:             fig_delta = px.bar(
 598:                 vergelijk,
 599:                 x="advies_type",
 600:                 y="verandering",
 601:                 color="verandering",
 602:                 color_continuous_scale=["#d73027", "#fee08b", "#1a9850"],
 603:                 color_continuous_midpoint=0,
 604:                 title="Verandering per adviestype (procentpunten)",
 605:                 labels={"advies_type": "Adviestype", "verandering": "Verandering (pp)"},
 606:                 height=400,
 607:             )
 608:             fig_delta.update_layout(xaxis_tickangle=-30)
 609:             st.plotly_chart(fig_delta, width="stretch")
 610:
 611:         bijstelling = (
 612:             na.groupby(["wijk_naam", "stadsdeel"], as_index=False)
 613:             .agg(
 614:                 totaal=("aantal_leerlingen", "sum"),
 615:                 bijgesteld=("bijgesteld_hoger", "sum")
 616:             )
 617:         )
 618:         bijstelling["pct_bijgesteld"] = (bijstelling["bijgesteld"] / bijstelling["totaal"] * 100).round(1)
 619:         # pct_niet_westers alleen opnemen als de kolom beschikbaar is
 620:         bijstelling_merge_kolommen = ["wijk_naam", "gem_inkomen"]
 621:         if "pct_niet_westers" in wijken_df.columns:
 622:             bijstelling_merge_kolommen.append("pct_niet_westers")
 623:         bijstelling = bijstelling.merge(
 624:             wijken_df[bijstelling_merge_kolommen],
 625:             on="wijk_naam", how="left"
 626:         )
 627:         bijstelling = bijstelling.sort_values("pct_bijgesteld", ascending=False)
 628:         if bijstelling["bijgesteld"].sum() > 0:
 629:             st.markdown("---")
 630:             st.subheader("📍 Bijgesteld advies per wijk")
 631:             st.markdown("""
 632:             In 2023-2024 konden leerlingen een **hoger bijgesteld advies** krijgen na de toets.
 633:             Hieronder zie je welke wijken hier het meest van profiteerden.
 634:             De verwachting is dat dit effect groter is in wijken met een lager inkomen.
 635:             """)
 636:
 637:             fig_bij = px.bar(
 638:                 bijstelling,
 639:                 x="wijk_naam",
 640:                 y="pct_bijgesteld",
 641:                 color="gem_inkomen",
 642:                 color_continuous_scale="RdYlGn",
 643:                 title="% leerlingen met omhoog bijgesteld advies (2023-2024)",
 644:                 labels={
 645:                     "wijk_naam": "Wijk",
 646:                     "pct_bijgesteld": "% bijgesteld hoger",
 647:                     "gem_inkomen": "Gem. inkomen (x€1.000)",
 648:                 },
 649:                 height=420,
 650:             )
 651:             fig_bij.update_layout(xaxis_tickangle=-35)
 652:             st.plotly_chart(fig_bij, width="stretch")
 653:
 654:             st.markdown("""
 655:             **Conclusie:** Wijken met een **lager gemiddeld inkomen** (rood/oranje) hebben een
 656:             **hoger percentage bijstellingen**. Dit is precies wat de doorstroomtoets beoogde:
 657:             kinderen die onderschat worden krijgen nu vaker een hoger advies.
 658:             """)
 659:         else:
 660:             st.markdown("---")
 661:             st.info("De huidige live DUO-bron bevat geen apart bruikbare gegevens over omhoog bijgestelde adviezen.")
 662:
 663:
 664: # ===============================================================
 665: # TAB 5 - VOORSPELLEND MODEL
 666: # ===============================================================
 667: with tab5:
 668:     st.header("🔮 Voorspellend model: welke wijk doet het beter dan verwacht?")
 669:     st.markdown("""
 670:     We bouwen een **lineair regressiemodel** dat probeert te voorspellen hoeveel
 671:     procent hoge adviezen een wijk zou moeten hebben op basis van:
 672:     - Gemiddeld inkomen
 673:     - % niet-westerse achtergrond
 674:     - % mensen met uitkering
 675:     - % laag opgeleiden
 676:
 677:     Wijken die **beter** scoren dan het model voorspelt, doen het goed ondanks hun
 678:     achterstand. Wijken die **slechter** scoren, verdienen meer aandacht.
 679:     """)
 680:
 681:     features = ["gem_inkomen", "pct_niet_westers", "pct_uitkering", "pct_laag_opgeleid"]
 682:     target   = "pct_hoog_advies"
 683:
 684:     # alleen rijen waar alle kolommen beschikbaar zijn
 685:     model_data = wijken_df[features + [target, "wijk_naam", "stadsdeel"]].dropna()
 686:
 687:     if len(model_data) >= 6:
 688:         X = model_data[features].values
 689:         y = model_data[target].values
 690:
 691:         # standaardiseren zodat de coëfficiënten vergelijkbaar zijn
 692:         scaler = StandardScaler()
 693:         X_sc   = scaler.fit_transform(X)
 694:
 695:         model = LinearRegression()
 696:         model.fit(X_sc, y)
 697:
 698:         y_pred = model.predict(X_sc)
 699:         residu = y - y_pred
 700:
 701:         # R² berekenen
 702:         ss_res = ((y - y_pred) ** 2).sum()
 703:         ss_tot = ((y - y.mean()) ** 2).sum()
 704:         r2     = 1 - ss_res / ss_tot
 705:

### Tab 6 - Data & Methoden

Dit is de uitleg-tab van het dashboard zelf.

Hier laat de app zien:
- welke databronnen zijn gebruikt
- hoe de APIs werken
- hoe datasets zijn gekoppeld
- ruwe tabellen

Waarom is dit belangrijk?

Omdat een dashboard niet alleen mooie grafieken moet tonen,
maar ook eerlijk moet laten zien **waar de cijfers vandaan komen**.

In de huidige versie is dat extra belangrijk, omdat:
- CBS live wordt gebruikt
- DUO live wordt gebruikt voor de algemene schooladviezen
- Amsterdam live wordt gebruikt voor scholen en wijkgrenzen
- de doorstroomtoets-tab zo nodig terugvalt op de projectdataset voor bijstellingen

In [15]:
toon_regels("app.py", 705, 860)

 705:
 706:         model_data = model_data.copy()
 707:         model_data["voorspeld"] = y_pred.round(1)
 708:         model_data["werkelijk"] = y.round(1)
 709:         model_data["residu"]    = residu.round(1)
 710:         model_data["prestatie"] = model_data["residu"].apply(
 711:             lambda r: "Beter dan verwacht" if r > 3
 712:             else "Slechter dan verwacht" if r < -3
 713:             else "Zoals verwacht"
 714:         )
 715:
 716:         st.markdown(f"**Model R² = {r2:.3f}** — het model verklaart {r2*100:.1f}% van de variatie in schooladvies.")
 717:
 718:         col1, col2 = st.columns(2)
 719:         with col1:
 720:             fig_model = px.scatter(
 721:                 model_data,
 722:                 x="voorspeld",
 723:                 y="werkelijk",
 724:                 color="prestatie",
 725:                 text="wijk_naam",
 726:                 color_discrete_map={
 727:                     "Beter dan verwacht":    "#1a9850",
 728:                     "Zoals verwacht":        "#78909c",
 729:                     "Slechter dan verwacht": "#d73027",
 730:                 },
 731:                 title="Voorspeld vs. werkelijk % hoog advies",
 732:                 labels={"voorspeld": "Voorspeld %", "werkelijk": "Werkelijk %"},
 733:                 height=450,
 734:             )
 735:             # diagonale lijn (perfecte voorspelling)
 736:             fig_model.add_shape(
 737:                 type="line",
 738:                 x0=model_data["voorspeld"].min(), y0=model_data["voorspeld"].min(),
 739:                 x1=model_data["voorspeld"].max(), y1=model_data["voorspeld"].max(),
 740:                 line=dict(color="gray", dash="dash"),
 741:             )
 742:             fig_model.update_traces(textposition="top center", textfont_size=9)
 743:             st.plotly_chart(fig_model, width="stretch")
 744:
 745:         with col2:
 746:             fig_residu = px.bar(
 747:                 model_data.sort_values("residu"),
 748:                 x="residu",
 749:                 y="wijk_naam",
 750:                 color="prestatie",
 751:                 orientation="h",
 752:                 color_discrete_map={
 753:                     "Beter dan verwacht":    "#1a9850",
 754:                     "Zoals verwacht":        "#78909c",
 755:                     "Slechter dan verwacht": "#d73027",
 756:                 },
 757:                 title="Afwijking van de voorspelling per wijk",
 758:                 labels={"residu": "Afwijking (procentpunten)", "wijk_naam": "Wijk"},
 759:                 height=450,
 760:             )
 761:             fig_residu.add_vline(x=0, line_color="black", line_dash="dash")
 762:             st.plotly_chart(fig_residu, width="stretch")
 763:
 764:         st.markdown("---")
 765:         st.subheader("📊 Gewicht van de factoren")
 766:
 767:         coef_df = pd.DataFrame({
 768:             "Factor":           features,
 769:             "Gewicht (bèta)":   model.coef_.round(3),
 770:             "Richting":         ["positief" if c > 0 else "negatief" for c in model.coef_],
 771:         }).sort_values("Gewicht (bèta)", key=abs, ascending=False)
 772:
 773:         fig_coef = px.bar(
 774:             coef_df,
 775:             x="Gewicht (bèta)",
 776:             y="Factor",
 777:             color="Richting",
 778:             orientation="h",
 779:             color_discrete_map={"positief": "#1a9850", "negatief": "#d73027"},
 780:             title="Invloed van elke factor op het % hoog schooladvies",
 781:             height=300,
 782:         )
 783:         fig_coef.add_vline(x=0, line_color="black")
 784:         st.plotly_chart(fig_coef, width="stretch")
 785:
 786:         st.markdown("""
 787:         **Hoe lees je dit?**
 788:         - Een **positief** gewicht betekent: hoe hoger de waarde, hoe meer hoge adviezen.
 789:         - Een **negatief** gewicht betekent: hoe hoger de waarde, hoe minder hoge adviezen.
 790:         - Inkomen heeft het grootste positieve effect, % niet-westers het grootste negatieve.
 791:         """)
 792:
 793:         # tabel met over/onderpresterende wijken
 794:         st.markdown("---")
 795:         st.subheader("🏆 Opvallende wijken")
 796:         top_beter   = model_data[model_data["prestatie"] == "Beter dan verwacht"][["wijk_naam", "stadsdeel", "werkelijk", "voorspeld", "residu"]]
 797:         top_slechter = model_data[model_data["prestatie"] == "Slechter dan verwacht"][["wijk_naam", "stadsdeel", "werkelijk", "voorspeld", "residu"]]
 798:
 799:         col1, col2 = st.columns(2)
 800:         with col1:
 801:             st.markdown("**Beter dan verwacht** (verdiend nader onderzoek naar good practices)")
 802:             st.dataframe(top_beter.sort_values("residu", ascending=False), hide_index=True, width="stretch")
 803:         with col2:
 804:             st.markdown("**Slechter dan verwacht** (verdienen extra aandacht)")
 805:             st.dataframe(top_slechter.sort_values("residu"), hide_index=True, width="stretch")
 806:     else:
 807:         st.warning("Te weinig data voor het regressiemodel. Pas de filters aan.")
 808:
 809:
 810: # ===============================================================
 811: # TAB 7 - DATA & METHODEN
 812: # ===============================================================
 813: with tab6:
 814:     st.header("📚 Data & Methoden")
 815:     st.markdown("""
 816:     In dit dashboard gebruiken we drie publieke databronnen. Hieronder leggen we uit
 817:     hoe de APIs werken en hoe we de data hebben gecombineerd.
 818:     """)
 819:
 820:     st.subheader("🔗 Databronnen")
 821:     for naam, bron in bronnen.items():
 822:         status = "✅ Live" if "Live" in bron else "⚠️ Eigen data"
 823:         st.markdown(f"**{status} — {naam}**")
 824:         st.caption(bron)
 825:
 826:     st.markdown("---")
 827:     st.subheader("🛠️ Hoe de APIs werken")
 828:
 829:     with st.expander("1. CBS OData v3 API — Kerncijfers Wijken en Buurten"):
 830:         st.markdown("""
 831:         **URL:** `https://opendata.cbs.nl/ODataApi/odata/85984NED/TypedDataSet`
 832:
 833:         De CBS OData API gebruikt het OData v3 protocol. Je kunt data filteren met `$filter`,
 834:         het aantal rijen beperken met `$top`, en het formaat kiezen met `$format=json`.
 835:
 836:         > **Let op:** De nieuwere v4-API (`odata4.cbs.nl`) is momenteel niet bereikbaar.
 837:         > We gebruiken daarom de stabielere v3-API via `opendata.cbs.nl`.
 838:         > In v3 heet het regio-veld `WijkenEnBuurten` in plaats van `RegioS`.
 839:
 840:         **Ons verzoek:**
 841:         ```
 842:         $filter=startswith(WijkenEnBuurten,'WK0363')   ← alleen Amsterdam-wijken
 843:         $top=200                                        ← maximaal 200 rijen
 844:         $format=json                                    ← JSON formaat
 845:         ```
 846:
 847:         **Dataset:** 85984NED = Kerncijfers Wijken en Buurten 2024.
 848:         Bevat: gemiddeld inkomen, % niet-westers, % uitkering, WOZ-waarde etc. per wijk.
 849:         """)
 850:
 851:     with st.expander("2. DUO Open Onderwijsdata — Schooladviezen (wpoadvies-v1)"):
 852:         st.markdown("""
 853:         **URL:** `https://onderwijsdata.duo.nl/api/3/action/package_show?id=wpoadvies-v1`
 854:
 855:         DUO gebruikt de CKAN API (ook gebruikt door data.overheid.nl).
 856:         Eerst halen we de metadata op (welke bestanden zijn beschikbaar?),
 857:         dan downloaden we de meest recente CSV.
 858:
 859:         **Bevat:** per school (BRIN-nummer), per schooljaar, per adviestype
 860:         (PrO, VMBO-BBL, VMBO-KBL, VMBO-TL, VMBO-TL/HAVO, HAVO, HAVO/VWO, VWO):

## 5. Uitleg van de tabellen in de app

Onderaan de app staan ook tabellen met ruwe data.

Dat is goed, want:
- grafieken geven een samenvatting
- tabellen laten de echte waarden zien

Voor beginners is dit een mooie regel:

**Gebruik een grafiek om een verhaal te vertellen, en een tabel om te controleren of het verhaal klopt.**

In [16]:
print("Voorbeeld van een wijktabel")
display(wijken_df[["wijk_naam", "stadsdeel", "gem_inkomen", "pct_hoog_advies", "pct_laag_advies"]].head(10))

print("Voorbeeld van een schooladviestabel")
display(duo_df[["school_naam", "wijk_naam", "schooljaar", "advies_type", "aantal_leerlingen", "pct"]].head(10))

Voorbeeld van een wijktabel

                 wijk_naam   stadsdeel  gem_inkomen  pct_hoog_advies  pct_laag_advies
0                  Centrum     Centrum    58.230000             94.8              NaN
1   Oud-West / De Baarsjes        West    54.133333             70.3              4.3
2               Westerpark        West    51.275000             73.8              NaN
3    Geuzenveld-Slotermeer  Nieuw-West    34.375000             49.8             13.9
4                   Osdorp  Nieuw-West    38.175000             48.9              8.6
5              Slotervaart  Nieuw-West    40.166667             54.0             11.9
6            Bos en Lommer        West    48.475000              NaN              NaN
7                 Oud-Zuid        Zuid    83.025000             89.7              1.4
8  De Pijp / Rivierenbuurt        Zuid    51.800000             80.0              NaN
9   Buitenveldert / Zuidas        Zuid    66.725000             80.5              NaN

Voorbeeld van een schooladviestabel

    school_naam              wijk_naam schooljaar        advies_type  aantal_leerlingen  pct
0  Prof. Dumont  Gaasperdam / Driemond  2018-2019           VMBO-BBL                  9  4.7
1  Prof. Dumont  Gaasperdam / Driemond  2019-2020           VMBO-BBL                 20  9.0
2  Prof. Dumont  Gaasperdam / Driemond  2020-2021           VMBO-BBL                 10  6.0
3  Prof. Dumont  Gaasperdam / Driemond  2021-2022  Praktijkonderwijs                  6  2.4
4  Prof. Dumont  Gaasperdam / Driemond  2021-2022           VMBO-BBL                 21  8.6
5  Prof. Dumont  Gaasperdam / Driemond  2022-2023  Praktijkonderwijs                  6  3.0
6  Prof. Dumont  Gaasperdam / Driemond  2022-2023           VMBO-BBL                 14  7.1
7  Prof. Dumont  Gaasperdam / Driemond  2023-2024           VMBO-BBL                 14  8.5
8  Tobiasschool               Oud-Zuid  2018-2019           VMBO-KBL                  6  1.0
9  Tobiasschool               Oud-Zuid  2019-2020           VMBO-BBL                  5  0.9

## 6. Wat moet je als beginner vooral onthouden?

Als je pas kort met data-analyse bezig bent, probeer dan vooral dit te onthouden:

1. Data ophalen is vaak maar het begin.
   Je moet data daarna bijna altijd nog opschonen en koppelen.

2. Een dashboard bestaat uit kleine stappen.
   Eerst data inladen, dan filteren, dan berekenen, dan tekenen.

3. Een grafiek is een vraag in beeldvorm.
   Vraag jezelf altijd af: wat wil ik hier laten zien?

4. Niet alles hoeft meteen perfect of slim.
   Duidelijke, simpele code is vaak beter dan ingewikkelde code.

5. Tabellen blijven belangrijk.
   Daarmee kun je controleren of je grafiek logisch is.

Als je deze 5 dingen begrijpt, dan begrijp je de basis van dit project al goed.